export * as HubDocker from "./docker.js"

import type { Entry } from "../types.js"

// Docker and Compose day-to-day operations.
export const entries: Entry[] = [
  {
    id: "docker.ps",
    title: "Running containers",
    description: "List containers with status, image and ports",
    category: "docker",
    requires: ["docker"],
    templates: { bash: "docker ps" },
  },
  {
    id: "docker.ps-all",
    title: "All containers",
    description: "Include stopped containers in the listing",
    category: "docker",
    requires: ["docker"],
    templates: { bash: "docker ps -a" },
  },
  {
    id: "docker.logs",
    title: "Container logs",
    description: "Tail the last N lines of a container's output",
    category: "docker",
    requires: ["docker"],
    templates: { bash: "docker logs --tail {lines} {container}" },
  },
  {
    id: "docker.logs-follow",
    title: "Follow container logs",
    description: "Stream logs until interrupted",
    category: "docker",
    requires: ["docker"],
    templates: { bash: "docker logs --follow {container}" },
  },
  {
    id: "docker.exec",
    title: "Run command in container",
    description: "Execute a command inside a running container",
    category: "docker",
    requires: ["docker"],
    templates: { bash: "docker exec {container} sh -c {command}" },
  },
  {
    id: "docker.images",
    title: "List images",
    description: "Images with size and creation time",
    category: "docker",
    requires: ["docker"],
    templates: { bash: "docker images" },
  },
  {
    id: "docker.prune",
    title: "Prune dangling resources",
    description: "Remove unused images, containers and networks",
    category: "docker",
    requires: ["docker"],
    danger: true,
    templates: { bash: "docker system prune -f" },
  },
  {
    id: "docker.disk-usage",
    title: "Docker disk usage",
    description: "Space taken by images, containers and volumes",
    category: "docker",
    requires: ["docker"],
    templates: { bash: "docker system df -v" },
  },
  {
    id: "docker.compose-up",
    title: "Compose up",
    description: "Start services defined in a compose file in detached mode",
    category: "docker",
    requires: ["docker"],
    templates: { bash: "docker compose up -d {service?}" },
  },
  {
    id: "docker.compose-logs",
    title: "Compose logs",
    description: "Tail logs across compose services",
    category: "docker",
    requires: ["docker"],
    templates: { bash: "docker compose logs --tail {lines} {service?}" },
  },
  {
    id: "docker.compose-ps",
    title: "Compose service status",
    description: "Status of services in the current compose project",
    category: "docker",
    requires: ["docker"],
    templates: { bash: "docker compose ps" },
  },
  {
    id: "docker.copy",
    title: "Copy from container",
    description: "Copy a file out of a container to the host",
    category: "docker",
    requires: ["docker"],
    templates: { bash: "docker cp {container}:{source} {destination}" },
  },
]
