export * as HubGit from "./git.js"

import type { Entry } from "../types.js"

// Git workflows: history, inspection, staging, branching.
export const entries: Entry[] = [
  {
    id: "git.status",
    title: "Compact status",
    description: "Short status with branch, staged, unstaged and untracked entries",
    category: "git",
    requires: ["git"],
    templates: { bash: "git status --short --branch" },
  },
  {
    id: "git.log-graph",
    title: "History with graph",
    description: "Decorated one-line history with branch graph",
    category: "git",
    requires: ["git"],
    templates: { bash: "git log --oneline --graph --decorate -n {limit}" },
  },
  {
    id: "git.log-file",
    title: "History of a file",
    description: "Commits that touched a specific path",
    category: "git",
    requires: ["git"],
    templates: { bash: "git log --oneline -n {limit} -- {path}" },
  },
  {
    id: "git.log-author",
    title: "History by author",
    description: "Commits authored by a given person",
    category: "git",
    requires: ["git"],
    templates: { bash: "git log --oneline --author={author} -n {limit}" },
  },
  {
    id: "git.log-search",
    title: "Search commit messages",
    description: "Find commits whose message matches a pattern",
    category: "git",
    requires: ["git"],
    templates: { bash: "git log --oneline --grep={pattern} -n {limit}" },
  },
  {
    id: "git.diff-staged",
    title: "Diff staged changes",
    description: "Show what will be committed",
    category: "git",
    requires: ["git"],
    templates: { bash: "git diff --staged" },
  },
  {
    id: "git.diff-branch",
    title: "Diff against a branch",
    description: "Compare working tree with another branch",
    category: "git",
    requires: ["git"],
    templates: { bash: "git diff {branch}" },
  },
  {
    id: "git.blame",
    title: "Blame a file",
    description: "Show last commit per line of a file",
    category: "git",
    requires: ["git"],
    templates: { bash: "git blame {path}" },
  },
  {
    id: "git.branch-list",
    title: "List branches by recency",
    description: "Local branches sorted by commit date",
    category: "git",
    requires: ["git"],
    templates: { bash: "git for-each-ref --sort=-committerdate refs/heads --format='%(refname:short) %(committerdate:relative)'" },
  },
  {
    id: "git.branch-clean",
    title: "Delete merged branches",
    description: "Remove local branches already merged into the current one",
    category: "git",
    requires: ["git"],
    danger: true,
    templates: { bash: "git branch --merged {branch} | grep -vE '^\\*|{branch}$' | xargs -r git branch -d" },
  },
  {
    id: "git.stash-list",
    title: "List stashes",
    description: "Show saved stashes with descriptions",
    category: "git",
    requires: ["git"],
    templates: { bash: "git stash list" },
  },
  {
    id: "git.untracked",
    title: "List untracked files",
    description: "Show files git does not yet track",
    category: "git",
    requires: ["git"],
    templates: { bash: "git ls-files --others --exclude-standard" },
  },
  {
    id: "git.file-size",
    title: "Largest files in history",
    description: "Biggest blobs currently tracked by the repository",
    category: "git",
    requires: ["git"],
    templates: { bash: "git ls-tree -r -l HEAD | sort -k4 -rn | head -{limit}" },
  },
  {
    id: "git.commit-count",
    title: "Count commits",
    description: "Total commit count, optionally since a date",
    category: "git",
    requires: ["git"],
    templates: { bash: "git rev-list --count {range}" },
  },
]
