export * as HubJson from "./json.js"

import type { Entry } from "../types.js"

// jq/yq one-liners for JSON and YAML manipulation.
export const entries: Entry[] = [
  {
    id: "json.pretty",
    title: "Pretty-print JSON",
    description: "Reformat JSON with two-space indentation",
    category: "json",
    requires: ["jq"],
    templates: { bash: "jq . {file}" },
  },
  {
    id: "json.field",
    title: "Extract a field",
    description: "Read a top-level or dotted field from JSON",
    category: "json",
    requires: ["jq"],
    templates: { bash: "jq -r {path} {file}" },
  },
  {
    id: "json.fields",
    title: "Extract multiple fields",
    description: "Project selected keys into a compact object",
    category: "json",
    requires: ["jq"],
    templates: { bash: "jq '{ {keys} }' {file}" },
  },
  {
    id: "json.filter-array",
    title: "Filter array elements",
    description: "Keep array elements matching a jq condition",
    category: "json",
    requires: ["jq"],
    templates: { bash: "jq '[.[] | select({condition})]' {file}" },
  },
  {
    id: "json.iterate-keys",
    title: "List object keys",
    description: "Print every top-level key, one per line",
    category: "json",
    requires: ["jq"],
    templates: { bash: "jq -r 'keys[]' {file}" },
  },
  {
    id: "json.length",
    title: "Array or object length",
    description: "Count elements of an array or keys of an object",
    category: "json",
    requires: ["jq"],
    templates: { bash: "jq 'length' {file}" },
  },
  {
    id: "json.flatten",
    title: "Flatten nested JSON",
    description: "Collapse nested objects into dotted keys",
    category: "json",
    requires: ["jq"],
    templates: { bash: "jq '[paths(scalars) as $p | {key: ($p | join(\".\")), value: getpath($p)}] | from_entries' {file}" },
  },
  {
    id: "json.validate",
    title: "Validate JSON",
    description: "Exit non-zero and report the error when JSON is malformed",
    category: "json",
    requires: ["jq"],
    templates: { bash: "jq empty {file}" },
  },
  {
    id: "json.sort-keys",
    title: "Sort object keys",
    description: "Recursively sort keys for stable, diffable JSON",
    category: "json",
    requires: ["jq"],
    templates: { bash: "jq --sort-keys . {file}" },
  },
  {
    id: "json.to-jsonl",
    title: "Array to JSON Lines",
    description: "Emit one JSON object per line for streaming tools",
    category: "json",
    requires: ["jq"],
    templates: { bash: "jq -c '.[]' {file}" },
  },
  {
    id: "yaml.get",
    title: "Read a YAML path",
    description: "Extract a value from YAML by dotted path",
    category: "json",
    requires: ["yq"],
    templates: { bash: "yq {path} {file}" },
  },
  {
    id: "yaml.pretty",
    title: "Pretty-print YAML",
    description: "Reformat YAML in place-friendly style",
    category: "json",
    requires: ["yq"],
    templates: { bash: "yq '.' {file}" },
  },
  {
    id: "yaml.to-json",
    title: "Convert YAML to JSON",
    description: "Transcode YAML into pretty JSON on stdout",
    category: "json",
    requires: ["yq"],
    templates: { bash: "yq -o=json '.' {file}" },
  },
  {
    id: "json.to-yaml",
    title: "Convert JSON to YAML",
    description: "Transcode JSON into YAML",
    category: "json",
    requires: ["yq"],
    templates: { bash: "yq -P '.' {file}" },
  },
]
