export * as HubWindows from "./windows.js"

import type { Entry } from "../types.js"

// PowerShell-flavoured entries for Windows hosts, written for both Windows
// PowerShell 5.1 (always present) and PowerShell 7. They are the Windows
// counterparts of the Linux-only system/process/network entries; on other
// platforms they are filtered out by `platforms`.
export const entries: Entry[] = [
  {
    id: "windows.processes",
    title: "Process list",
    description: "Top CPU-consuming processes on Windows",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Get-Process | Sort-Object CPU -Descending | Select-Object -First {limit} Name, CPU, WorkingSet" },
  },
  {
    id: "windows.listener",
    title: "Listening ports",
    description: "TCP listeners with owning process",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Get-NetTCPConnection -State Listen | Select-Object LocalAddress, LocalPort, OwningProcess" },
  },
  {
    id: "windows.service",
    title: "Service status",
    description: "Status of a Windows service",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Get-Service -Name {name} | Format-List Name, Status, StartType" },
  },
  {
    id: "windows.files",
    title: "Recursive file search",
    description: "Find files by wildcard under a path",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Get-ChildItem -Path {path} -Recurse -Filter {pattern} | Select-Object FullName, Length" },
  },
  {
    id: "windows.disk",
    title: "Drive free space",
    description: "Capacity and free space of all drives",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Get-PSDrive -PSProvider FileSystem | Select-Object Name, @{n='Used';e={[math]::Round($_.Used/1GB,1)}}, @{n='Free';e={[math]::Round($_.Free/1GB,1)}}" },
  },
  {
    id: "windows.env",
    title: "Environment variables",
    description: "Machine and user environment variables sorted",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "[Environment]::GetEnvironmentVariables() | Sort-Object keys | Format-Table -AutoSize" },
  },
  {
    id: "windows.winget-update",
    title: "Upgradable packages",
    description: "List packages with available upgrades",
    category: "windows",
    platforms: ["win32"],
    requires: ["winget"],
    templates: { pwsh: "winget upgrade --include-unknown" },
  },
  {
    id: "windows.eventlog",
    title: "Recent error events",
    description: "Last error entries from the system event log",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Get-EventLog -LogName System -EntryType Error -Newest {limit} | Format-Table TimeGenerated, Source, Message -AutoSize" },
  },
  {
    id: "windows.kill",
    title: "Stop a process",
    description: "Terminate a process by name",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    danger: true,
    templates: { pwsh: "Stop-Process -Name {name} -Force" },
  },
  {
    id: "windows.temp-clean",
    title: "Clear temp folders",
    description: "Delete files in the user temp directory",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    danger: true,
    templates: { pwsh: "Remove-Item -Path \"$env:TEMP\\*\" -Recurse -Force -ErrorAction SilentlyContinue" },
  },
  {
    id: "windows.os",
    title: "Windows version",
    description: "Edition, version, build and architecture of Windows",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Get-CimInstance Win32_OperatingSystem | Format-List Caption, Version, BuildNumber, OSArchitecture" },
  },
  {
    id: "windows.memory",
    title: "Memory usage",
    description: "Total and free physical memory in GB",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: {
      pwsh: "Get-CimInstance Win32_OperatingSystem | Format-List @{n='TotalGB';e={[math]::Round($_.TotalVisibleMemorySize/1MB,1)}}, @{n='FreeGB';e={[math]::Round($_.FreePhysicalMemory/1MB,1)}}",
    },
  },
  {
    id: "windows.cpu",
    title: "CPU model and cores",
    description: "Processor model, core and thread count, max clock",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Get-CimInstance Win32_Processor | Format-List Name, NumberOfCores, NumberOfLogicalProcessors, MaxClockSpeed" },
  },
  {
    id: "windows.uptime",
    title: "System uptime",
    description: "Last boot time and how long Windows has been running",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: {
      pwsh: "$b = (Get-CimInstance Win32_OperatingSystem).LastBootUpTime; \"Booted $b, up $((Get-Date) - $b)\"",
    },
  },
  {
    id: "windows.ping",
    title: "Ping a host",
    description: "ICMP reachability and round-trip times",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Test-Connection -Count {count} {host}" },
  },
  {
    id: "windows.kill-pid",
    title: "Terminate a process by PID",
    description: "Force-stop the process with the given id",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    danger: true,
    templates: { pwsh: "Stop-Process -Id {pid} -Force" },
  },
  {
    id: "windows.find-process",
    title: "Find a process by name",
    description: "Running processes whose name matches a wildcard pattern",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Get-Process -Name {pattern} | Select-Object Id, Name, CPU, WorkingSet, Path" },
  },
  {
    id: "windows.port-owner",
    title: "Process listening on a port",
    description: "Which process owns a listening TCP port",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: {
      pwsh: "Get-NetTCPConnection -State Listen -LocalPort {port} | Select-Object LocalAddress, LocalPort, OwningProcess, @{n='Process';e={(Get-Process -Id $_.OwningProcess).Name}}",
    },
  },
]
