export * as HubWindows from "./windows.js"

import type { Entry } from "../types.js"

// PowerShell-flavoured entries for Windows hosts. Only the pwsh backend is
// offered; on other platforms these entries are filtered out by `platforms`.
export const entries: Entry[] = [
  {
    id: "windows.processes",
    title: "Process list",
    description: "Top CPU-consuming processes on Windows",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Get-Process | Sort-Object CPU -Descending | Select-Object -First {limit} Name, CPU, WorkingSet" },
  },
  {
    id: "windows.listener",
    title: "Listening ports",
    description: "TCP listeners with owning process",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Get-NetTCPConnection -State Listen | Select-Object LocalAddress, LocalPort, OwningProcess" },
  },
  {
    id: "windows.service",
    title: "Service status",
    description: "Status of a Windows service",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Get-Service -Name {name} | Format-List Name, Status, StartType" },
  },
  {
    id: "windows.files",
    title: "Recursive file search",
    description: "Find files by wildcard under a path",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Get-ChildItem -Path {path} -Recurse -Filter {pattern} | Select-Object FullName, Length" },
  },
  {
    id: "windows.disk",
    title: "Drive free space",
    description: "Capacity and free space of all drives",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Get-PSDrive -PSProvider FileSystem | Select-Object Name, @{n='Used';e={[math]::Round($_.Used/1GB,1)}}, @{n='Free';e={[math]::Round($_.Free/1GB,1)}}" },
  },
  {
    id: "windows.env",
    title: "Environment variables",
    description: "Machine and user environment variables sorted",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "[Environment]::GetEnvironmentVariables() | Sort-Object keys | Format-Table -AutoSize" },
  },
  {
    id: "windows.winget-update",
    title: "Upgradable packages",
    description: "List packages with available upgrades",
    category: "windows",
    platforms: ["win32"],
    requires: ["winget"],
    templates: { pwsh: "winget upgrade --include-unknown" },
  },
  {
    id: "windows.eventlog",
    title: "Recent error events",
    description: "Last error entries from the system event log",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    templates: { pwsh: "Get-EventLog -LogName System -EntryType Error -Newest {limit} | Format-Table TimeGenerated, Source, Message -AutoSize" },
  },
  {
    id: "windows.kill",
    title: "Stop a process",
    description: "Terminate a process by name",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    danger: true,
    templates: { pwsh: "Stop-Process -Name {name} -Force" },
  },
  {
    id: "windows.temp-clean",
    title: "Clear temp folders",
    description: "Delete files in the user temp directory",
    category: "windows",
    platforms: ["win32"],
    requires: ["pwsh"],
    danger: true,
    templates: { pwsh: "Remove-Item -Path \"$env:TEMP\\*\" -Recurse -Force -ErrorAction SilentlyContinue" },
  },
]
